# Generated by Django 4.2 on 2023-05-23 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_delete_ratingplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('lenght_game', models.IntegerField(blank=True, default=0, null=True)),
                ('dateTime', models.DateTimeField(blank=True, null=True)),
                ('user_id_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_B', to=settings.AUTH_USER_MODEL)),
                ('user_id_W', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_W', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
