# Generated by Django 4.2 on 2023-05-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistory',
            old_name='user_id_B',
            new_name='user_B',
        ),
        migrations.RenameField(
            model_name='gamehistory',
            old_name='user_id_W',
            new_name='user_W',
        ),
    ]
