# Generated by Django 4.2 on 2023-05-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_user_id_b_gamehistory_user_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='username_B',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='username_W',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
