# Generated by Django 4.2 on 2023-05-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
