# Generated by Django 4.2 on 2023-05-18 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_game', models.CharField(max_length=6)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_connections1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_connections2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
