# Generated by Django 4.2 on 2023-05-18 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sessionconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionconnection',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_connections2', to=settings.AUTH_USER_MODEL),
        ),
    ]
