# Generated by Django 4.2 on 2023-05-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sessionconnection_expiry_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionconnection',
            name='expiry_time',
        ),
        migrations.AddField(
            model_name='sessionconnection',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
