# Generated by Django 4.2 on 2023-05-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_sessionconnection_expiry_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionconnection',
            name='type_game',
        ),
        migrations.AddField(
            model_name='sessionconnection',
            name='min',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionconnection',
            name='sec',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
