# Generated by Django 4.2 on 2023-05-23 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_ratingplayer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingPlayer',
        ),
    ]
