# Generated by Django 4.2 on 2023-06-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionconnection',
            name='sec',
        ),
        migrations.AddField(
            model_name='sessionconnection',
            name='desk',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
