# Generated by Django 4.2 on 2023-06-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_sessionconnection_sec_sessionconnection_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionconnection',
            name='cords_ancle',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
