# Generated by Django 4.2 on 2023-06-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_game', models.IntegerField()),
                ('queue_step', models.IntegerField()),
                ('moves', models.TextField(max_length=200)),
                ('user_id_W', models.IntegerField(default=5)),
                ('user_id_B', models.IntegerField(default=5)),
                ('step', models.CharField(max_length=10)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
