# Generated by Django 4.2 on 2023-06-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
