# Generated by Django 4.2 on 2023-06-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_alter_steps_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='moves',
        ),
    ]
