# Generated by Django 4.2 on 2023-06-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_remove_steps_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='moves',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
